# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Elsiwhere
email: rune@addin.dk
description: > # this means to ignore newlines until "baseurl:"
  Find oplevelser for hele familien i Helsingør Kommune
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://elsiwhere.addin.dk" # the base hostname & protocol for your site
twitter_username: runetvilum
github_username:  runetvilum

# Build settings
markdown: kramdown
exclude: [ 'node_modules', '*.json' ]
collections:
  category:
    output: true
  subcategory:
    output: true
  sight:
    output: true
